### ISSUE TITLE
计步函数

### ISSUE THREAD

**Issue by 140ai** [Yohox/IBeaconLocationMiniprogram#1]
请问计步函数的参数怎么调，太敏感了，

**Comment by Yohox** [comment]
主要调整这个文件：https://github.com/Yohox/IBeaconLocationMiniProgram/blob/master/miniprogram/utils/step_algorithm.js
的
//动态阈值需要动态的数据，这个值用于这些动态数据的阈值
let initialValue = 0.8;
//初始阈值
let ThreadValue = 0.7;

//初始范围
let minValue = 9.0;
let maxValue = 18.6;
这四个参数

**Comment by Yohox** [comment]
可以参考文章：https://x.yoho.ac.cn/2020/08/29/yuque/%E5%9F%BA%E4%BA%8EIBeacon+%E6%83%AF%E6%80%A7%E5%AE%9E%E7%8E%B0%E7%B2%BE%E7%A1%AE%E5%AE%9E%E6%97%B6%E5%AF%BC%E8%88%AA%E5%B0%8F%E7%A8%8B%E5%BA%8F/
